"""add telegram_id to users

Revision ID: 57d49404df32
Revises: e139bcae5a1c
Create Date: 2026-07-04 16:15:51.476380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '57d49404df32'
down_revision: Union[str, None] = 'e139bcae5a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
