"""security guards: otp attempts, allocation unique, stop paid

Revision ID: dcf3a927984b
Revises: c7d2a91e4f63
Create Date: 2026-08-02 23:14:06.413849
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "dcf3a927984b"
down_revision: Union[str, None] = "c7d2a91e4f63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_allocations_order_item_offer", "allocations", ["order_item_id", "offer_id"]
    )
    op.add_column(
        "otp_codes",
        sa.Column(
            "attempts", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "route_stops",
        sa.Column(
            "paid", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # Mavjud qatorlar uchun server_default saqlanadi, yangi kod client-default'ni
    # o'zi beradi.
    op.alter_column("otp_codes", "attempts", server_default=None)
    op.alter_column("route_stops", "paid", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("route_stops", "paid")
    op.drop_column("otp_codes", "attempts")
    op.drop_constraint("uq_allocations_order_item_offer", "allocations", type_="unique")
    # ### end Alembic commands ###
