"""initial schema

Revision ID: e139bcae5a1c
Revises: 
Create Date: 2026-07-03 20:00:37.935951
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e139bcae5a1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_uz', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.Enum('kg', 'dona', 'bogʻlam', name='unit'), nullable=False),
    sa.Column('category', sa.Enum('sabzavot', 'meva', 'kokat', name='category'), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('payme', 'click', name='card_provider'), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('brand', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', name='uq_price_product_date')
    )
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    op.create_table('farmers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('card_token', sa.String(length=500), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=40), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('app', 'bot', 'call', 'collector', name='source'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('price_corridor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'date', name='uq_corridor_product_date')
    )
    op.create_index(op.f('ix_price_corridor_date'), 'price_corridor', ['date'], unique=False)
    op.create_table('restaurants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('credit_limit', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('cash', 'card', 'credit', name='payment_type'), nullable=False),
    sa.Column('tariff', sa.Enum('start', 'business', 'premium', name='tariff'), nullable=False),
    sa.Column('tariff_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('collector_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'done', name='route_status'), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_date'), 'routes', ['date'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'restaurant', 'collector', 'admin', name='role'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('auto_approved', 'needs_review', 'approved', 'rejected', name='offer_status'), nullable=False),
    sa.Column('source', sa.Enum('app', 'bot', 'call', 'collector', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_date_status', 'offers', ['date', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_slot', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('new', 'allocated', 'collecting', 'in_transit', 'delivered', 'paid', 'cancelled', name='order_status'), nullable=False),
    sa.Column('total_sum', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('cash', 'card', 'credit', name='payment_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_date_status', 'orders', ['delivery_date', 'status'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('planned_kg', sa.Integer(), nullable=False),
    sa.Column('actual_kg', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Enum('A', 'B', 'C', name='quality'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'skipped', name='stop_status'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_route_stops_route_seq', 'route_stops', ['route_id', 'seq'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.Column('sell_price_per_kg', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('payout', 'invoice', name='payment_kind'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('card', 'cash', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='payment_status'), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('kg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_index('ix_route_stops_route_seq', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('ix_orders_date_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_offers_date_status', table_name='offers')
    op.drop_table('offers')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_routes_date'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_price_corridor_date'), table_name='price_corridor')
    op.drop_table('price_corridor')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_table('sms_log')
    op.drop_table('products')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
